In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [5]:
data = {
    'Weight': [2,4,5,3,6,5,7],
     'Price': [35, 60, 20, 50, 50, 55, 60]
}
df = pd.DataFrame(data)
df
    

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

Task 01:
Your objective is to manually compute the slope (M) and y-intercept (C) using
Ordinary Least Squares Linear Regression. Once determined, apply these values to
predict the price when the vegetable weight is 6.

In [9]:
x = df['Weight']
y= df['Price']


In [10]:
mean_x = np.mean(x)
mean_y = np.mean(y)

In [13]:
mean_x


4.571428571428571

In [15]:
mean_y

47.142857142857146

In [16]:
dev_x = x - mean_x
dev_y = y - mean_y

In [17]:
coeficient_m = np.sum(dev_x * dev_y) / np.sum(dev_x **2)
coeficient_m

2.620967741935484

In [18]:
intercept_c = mean_y - coeficient_m * mean_x
intercept_c

35.16129032258065

In [19]:
(coeficient_m * 6) + intercept_c


50.88709677419355

Task 02:
Compute the residuals for each data point.

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
reg =  LinearRegression()

In [22]:
reg.fit(df[['Weight']] , df[['Price']])

LinearRegression()

In [23]:
reg.coef_

array([[2.62096774]])

In [24]:
reg.intercept_

array([35.16129032])

In [25]:
reg.predict([[6]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[50.88709677]])

In [27]:
Predicted_Price = reg.predict(df[['Weight']])
Predicted_Price

array([[40.40322581],
       [45.64516129],
       [48.26612903],
       [43.02419355],
       [50.88709677],
       [48.26612903],
       [53.50806452]])

In [29]:
df['Predicted_Price'] = Predicted_Price

In [30]:
df['Residual'] = df['Price'] - df['Predicted_Price']
df

Weight  Price  Predicted_Price   Residual
0       2     35        40.403226  -5.403226
1       4     60        45.645161  14.354839
2       5     20        48.266129 -28.266129
3       3     50        43.024194   6.975806
4       6     50        50.887097  -0.887097
5       5     55        48.266129   6.733871
6       7     60        53.508065   6.491935

Task 03:
Calculate both the Mean Squared Error (MSE) and Mean Absolute Error (MAE).

In [32]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [37]:
mse  = mean_squared_error(df['Price'],df['Predicted_Price'])
mse

167.30990783410135

In [35]:
mae = mean_absolute_error(df['Price'],df['Predicted_Price'])
mae

9.87327188940092

Final Task:
Generate an Excel file for the given dataset. Utilize Python for all the calculations.

In [42]:
Generate_an_Excel_file = df.to_excel('output1.xlsx', index=False)
